apiVersion: v1
kind: Secret
metadata:
  name: aegis-server-env
  namespace: aegis-casino
  labels:
    secret: aegis-server-env
type: Opaque
stringData:
  # Replace these with your actual production values
  PORT: "3001"
  # CORS_ORIGIN: "https://your-client-domain.com"
  CORS_ORIGIN: "*"
  
