apiVersion: v1
kind: Service
metadata:
  name: aegis-server-svc
  namespace: aegis-casino
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: websocket
  selector:
    app: aegis-server
