# ==========================================
# STAGE 1: Prune the Monorepo
# ==========================================
FROM node:22-slim AS pruner
WORKDIR /usr/src/app

CMD ["npm", "install"]

COPY . .

RUN npm prune aegis-server --docker

# ==========================================
# STAGE 2: Install & Build
# ==========================================
FROM node:22-slim AS builder
WORKDIR /usr/src/app

#COPY --from=pruner --chown=node:node /usr/src/app/package-lock.json ./package-lock.json
COPY --from=pruner --chown=node:node . .

RUN npm ci

# Now copy the isolated source code
# COPY --from=pruner /usr/src/app/out/full/ .
COPY --from=pruner --chown=node:node /usr/src/app .

RUN npm ci --omit=dev

# COPY . .

# ==========================================
# STAGE 3: Run the Production Server
# ==========================================
FROM node:22-slim AS runner
WORKDIR /usr/src/app

ENV NODE_ENV=production

# Create a non-root user for security (Standard security practice for crypto apps)
#RUN groupadd -r aegisgroup && useradd -r -g aegisgroup aegisuser
#RUN chown -R aegisuser:aegisgroup /usr/src
# COPY --from=builder --chown=aegisuser:aegisgroup /usr/src/app/apps/casino-web/.next/standalone ./

#COPY --from=builder --chown=aegisuser:aegisgroup /usr/src/app/aegis-server/.next/standalone ./
#COPY --from=builder --chown=aegisuser:aegisgroup /usr/src/app/aegis-server/.next/static ./aegis-server/.next/static
#COPY --from=builder --chown=aegisuser:aegisgroup /usr/src .
COPY --from=builder --chown=node:node /usr/src/app/node_modules ./node_modules
COPY --chown=node:node . .

USER node

EXPOSE 3001

CMD ["npx", "tsx", "server.js"]

