import express from 'express';
import fs from 'node:fs';
import https from 'node:https';
import process from 'node:process';
import path from 'node:path';   
import dotenv from 'dotenv';
import cors from 'cors';
import crypto from 'crypto';
import cron from 'node-cron';
import { fileURLToPath } from 'url';
import { Server } from 'socket.io';
import { createClient } from '@supabase/supabase-js';
import { fetchDailySeed } from './src/workers/daily-vrf-seed.js'; 

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 🚨 CHANGED: Point one folder up to the master .env file
dotenv.config({ path: path.join(__dirname, '../.env') });

const PORT = process.env.PORT || 3001;
const CORS_ORIGIN = process.env.CORS_ORIGIN || '*';
const TICK_RATE_MS = 50;
const ROUND_START_TIME_SEC = 10;
const ROUND_COOLDOWN_MS = 5000;
const MAX_CHAT_HISTORY = 50;
const HOUSE_EDGE_RTP = 50; // 1 in 50 instant crash (98% RTP)

const app = express();
app.use(cors({ origin: CORS_ORIGIN }));

app.get('/', (_req, res) => {
  res.send('🟢 Aegis Crash Server is running and ready for Socket.io connections!');
});

// Load the SSL certificates generated by Next.js
const options = {
  key: fs.readFileSync(path.join(__dirname, '/certificates/key.pem')),
  cert: fs.readFileSync(path.join(__dirname, '/certificates/cert.pem'))
};

const httpsServer = https.createServer(options, app);
const io = new Server(httpsServer, {
  cors: { origin: CORS_ORIGIN, methods: ["GET", "POST"] }
});

// Initialize Supabase Service Role client (Requires the master key to check global tables)
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey ) {
  console.error("❌ Missing required environment variables. Check your .env file.");
  process.exit(0);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  db: {
    schema: 'aegis_project_schema'
  }
});

// 🚨 NEW: Dynamic Chainlink Seed Variables
let ACTIVE_SERVER_SEED = null;
let ACTIVE_SALT = null;
let ACTIVE_VRF_REQUEST_ID = null;

async function loadLatestSeed() {
  const { data, error } = await supabase
    .from('daily_seeds')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (error || !data) {
    console.warn("⚠️ No seed found in DB! Using temporary local seed. Run your VRF worker soon!");
    ACTIVE_SERVER_SEED = crypto.randomBytes(32).toString('hex');
    ACTIVE_SALT = "TEMPORARY_LOCAL_SALT";
  } else {
    ACTIVE_SERVER_SEED = data.chainlink_seed;
    ACTIVE_SALT = data.casino_salt;
    ACTIVE_VRF_REQUEST_ID = data.vrf_request_id;
    console.log(`🔐 Loaded Provably Fair Seed (VRF Req: ${ACTIVE_VRF_REQUEST_ID})`);
  }
}

supabase.channel('seed-updates')
  .on('postgres_changes', { event: 'INSERT', schema: 'aegis_project_schema', table: 'daily_seeds' }, (payload) => {
    console.log('\n🔄 NEW CHAINLINK SEED DETECTED! Updating game math for the next round...');
    ACTIVE_SERVER_SEED = payload.new.chainlink_seed;
    ACTIVE_SALT = payload.new.casino_salt;
    ACTIVE_VRF_REQUEST_ID = payload.new.vrf_request_id;
  })
  .subscribe();

// Run exactly at midnight every day
cron.schedule('0 0 * * *', () => {
  console.log('Midnight reached. Executing daily VRF fetch...');
  fetchDailySeed();
});

// 🚨 ADD THIS FOR TESTING: Force a fetch immediately when the server boots!
console.log('Forcing an initial VRF fetch for testing...');
fetchDailySeed();

let currentRoundId = 1;
const gameState = {
  status: 'starting',
  multiplier: 1.00,
  crashPoint: 0,
  timeRemaining: 20,
  roundId: currentRoundId,
  activeBets: {},
  history: [] 
};

const chatHistory = [];

// 🚨 CHANGED: Now uses dynamic Chainlink seeds
function generateCrashPoint(serverSeed, salt, roundId) {
  // Safe fallback if the DB hasn't loaded yet
  if (!serverSeed || !salt) return 1.00;

  const hash = crypto.createHmac('sha256', serverSeed).update(`${salt}:${roundId}`).digest('hex');
  const h = parseInt(hash.substring(0, 13), 16);
  const e = Math.pow(2, 52);

  // 98% RTP (1 in 50 instant crash)
  if (h % HOUSE_EDGE_RTP === 0) return 1.00;

  const crashPoint = Math.floor((100 * e - h) / (e - h)) / 100.0;
  return Math.min(Math.max(1.00, crashPoint), 1000000); 
}

async function runGameLoop() {
  // 🚨 NEW: Wait for the database to load the seed before starting the first round!
  await loadLatestSeed();

  while (true) {
    gameState.status = 'starting';
    gameState.multiplier = 1.00;
    gameState.activeBets = {};
    gameState.timeRemaining = ROUND_START_TIME_SEC;
    gameState.roundId = currentRoundId;
    
    console.log(`\n🟢 NEW ROUND [${currentRoundId}]: Accepting Bets...`);
    
    while (gameState.timeRemaining > 0) {
      io.emit('game-tick', gameState);
      await new Promise(resolve => setTimeout(resolve, 1000));
      gameState.timeRemaining--;
    }

    gameState.status = 'in-progress';
    // 🚨 CHANGED: Pass the active global variables into the math generator
    gameState.crashPoint = generateCrashPoint(ACTIVE_SERVER_SEED, ACTIVE_SALT, currentRoundId);
    console.log(`🚀 ROCKET LAUNCHED! (Secret Crash Point: ${gameState.crashPoint}x)`);

    while (gameState.multiplier < gameState.crashPoint) {
      gameState.multiplier += (gameState.multiplier * 0.005); 
      if (gameState.multiplier > gameState.crashPoint) gameState.multiplier = gameState.crashPoint;

      for (const [userId, bet] of Object.entries(gameState.activeBets)) {
        if (!bet.cashedOut && gameState.multiplier >= bet.targetMultiplier) {
          bet.cashedOut = true;
          bet.winnings = bet.betAmount * bet.targetMultiplier;
          
          supabase.from('profiles').select('balance_usd').eq('id', userId).single().then(({ data }) => {
            if (data) supabase.from('profiles').update({ balance_usd: data.balance_usd + bet.winnings }).eq('id', userId);
          });

          io.to(bet.socketId).emit('bet-won');
        }
      }

      io.emit('game-tick', gameState);
      await new Promise(resolve => setTimeout(resolve, TICK_RATE_MS)); 
    }

    gameState.status = 'crashed';
    gameState.history.push(parseFloat(gameState.multiplier.toFixed(2)));
    if (gameState.history.length > 10) gameState.history.shift();

    // 🚨 CHANGED: Hash the round results against the Chainlink seed for player verification
    const roundHash = crypto.createHmac('sha256', ACTIVE_SERVER_SEED).update(`${ACTIVE_SALT}:${currentRoundId}`).digest('hex');
    console.log(`💥 CRASHED AT ${gameState.multiplier.toFixed(2)}x! (Provable Hash: ${roundHash})`);
    
    io.emit('game-tick', gameState);
    
    currentRoundId++;
    await new Promise(resolve => setTimeout(resolve, ROUND_COOLDOWN_MS));
  }
}

async function handlePlaceBet(socket, { token, betAmount, targetMultiplier }) {
  if (gameState.status !== 'starting') {
    return socket.emit('bet-error', 'Round is already in progress!');
  }
  
  try {
    // 🚨 SECURITY: Strict Input Validation
    if (typeof betAmount !== 'number' || betAmount <= 0) throw new Error('Invalid bet amount');
    if (typeof targetMultiplier !== 'number' || targetMultiplier <= 1.0) throw new Error('Invalid target multiplier');

    const { data: { user }, error } = await supabase.auth.getUser(token);
    if (error || !user) throw new Error('Unauthorized');

    // 🚨 SECURITY: Prevent double betting in the same round
    if (gameState.activeBets[user.id]) {
      throw new Error('You have already placed a bet for this round');
    }

    // 🚨 TODO (SECURITY): Replace with a Supabase RPC call for atomic decrement 
    // to avoid TOCTOU (Race condition) vulnerability.
    const { data: profile } = await supabase.from('profiles').select('balance_usd').eq('id', user.id).single();
    if (!profile || profile.balance_usd < betAmount) throw new Error('Insufficient balance');

    await supabase.from('profiles').update({ balance_usd: profile.balance_usd - betAmount }).eq('id', user.id);
    
    gameState.activeBets[user.id] = { socketId: socket.id, betAmount, targetMultiplier, cashedOut: false, winnings: 0 };
    socket.emit('bet-accepted');
  } catch (err) {
    socket.emit('bet-error', err.message);
  }
}

async function handleSendMessage(socket, { token, message }) {
  try {
    // 🚨 SECURITY: Type checking and trimming
    if (typeof message !== 'string' || message.trim() === '') return;
    const cleanMessage = message.trim().substring(0, 150);

    const { data: { user }, error } = await supabase.auth.getUser(token);
    if (error || !user) throw new Error('Unauthorized');

    const username = "P" + user.id.substring(0, 4).toUpperCase();
    const chatMsg = { id: crypto.randomUUID(), username, message: cleanMessage, time: new Date().toISOString() };

    chatHistory.push(chatMsg);
    if (chatHistory.length > MAX_CHAT_HISTORY) chatHistory.shift(); 
    
    io.emit('new-message', chatMsg);
  } catch {
    socket.emit('chat-error', 'Sign in to chat!');
  }
}

io.on('connection', (socket) => {
  socket.emit('game-tick', gameState);
  socket.emit('chat-history', chatHistory);

  socket.on('place-bet', (data) => handlePlaceBet(socket, data));
  socket.on('send-message', (data) => handleSendMessage(socket, data));
});

httpsServer.listen(PORT, () => {
  console.log(`🔒 SECURE Aegis Crash Engine running on port ${PORT}`);
  runGameLoop();
});
